// <auto-generated />
namespace ComprasCartonesLGP.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddVendedor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddVendedor));
        
        string IMigrationMetadata.Id
        {
            get { return "202110051329266_Add-Vendedor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
