// <auto-generated />
namespace ComprasCartonesLGP.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cambiosCompraSolicitud : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cambiosCompraSolicitud));
        
        string IMigrationMetadata.Id
        {
            get { return "202109061736004_cambiosCompraSolicitud"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
