// <auto-generated />
namespace ComprasCartonesLGP.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class parametros : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(parametros));
        
        string IMigrationMetadata.Id
        {
            get { return "202111091749367_parametros"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
